# Generated by Django 4.2.1 on 2023-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_chathistory_e_counselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='e_counselling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='type',
            field=models.CharField(choices=[('L', 'Liquid'), ('T', 'Tablet'), ('C', 'Capsule')], max_length=1),
        ),
    ]
