# Generated by Django 4.2.1 on 2023-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='imgsrc',
            field=models.CharField(default='doctor', max_length=20),
        ),
    ]
