# Generated by Django 4.2.1 on 2023-06-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_therapist_imgsrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='imgsrc',
        ),
    ]
